### PR TITLE
 Shared queues scheduler

### PR DESCRIPTION
**Pull request by lulf**
@grs 

This adds a QueueScheduler implementation based on Kubernetes watches and brokers connecting to it. I will later convert to retrieve the address configuration using configserve (have to modify the format to expose the group id as well).

This piece of code is not hooked in anywere, as it is my intent to add a second PR that activates the scheduler once the required modifications to the broker config and openshift templates are made. 

I can also move it to a separate process if you think that makes more sense.

### CODE REVIEW

**Comment by grs** [comment]
What about 'flattening' addresses in configserv, and adding a group_id attribute to all addresses? Means things that don't care about groups can ignore them.

**Comment by lulf** [comment]
@grs Good point. I'll change that. Btw, I have moved the scheduler here: https://github.com/EnMasseProject/queue-scheduler

**Comment by grs** [comment]
Oops that comment was actually supposed to go against https://github.com/EnMasseProject/subserv/pull/13/files not this one.

**Comment by lulf** [comment]
@grs Got it. It applies to the scheduler as well, as it has to parse the same payload :)

**Comment by lulf** [comment]
Closing as this has been moved to queue-scheduler repo

**Pull request closed without merging**
